version: "3.8"

services:
  storage:
    build: .
    environment:
      - STORAGE_LIMIT_MB=300
      - BUILDER_LIMIT_MB=500
    volumes:
      - storage_data:/app/data
    ports:
      - "8000:8000"
    restart: always

volumes:
  storage_data:
